import Foundation

class HomeViewModel {
    var data: [NewsFeed] = [
        NewsFeed(id: "6933a53f-18b1-4f2f-b510-c41f9a973aff", name: "Theodore Ziemann", avatar: "https://avatars.githubusercontent.com/u/41429422", content: "Carmen autus patruus debilito conqueror confugo vesco tendo spoliatio cavus. Alo tardus conventus caste absque curis. Tunc solus admiratio. Confido doloremque caterva baiulus. Curiositas sollers textilis maxime.", image: nil),
        NewsFeed(id: "e6f18305-46d8-42e9-9bc0-f996fe8268b1", name: "Marjorie Gottlieb", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/224.jpg", content: "Alii clibanus decretum cornu adipiscor sortitus contigo.", image: nil),
        NewsFeed(id: "60c36b68-b7be-4021-bf56-1421ce1bb96b", name: "Brent Weissnat", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/828.jpg", content: "Amoveo cupressus artificiose adsidue dolorum absconditus. Aliquam bellicus adhaero cubitum volaticus paens adicio inventore. Sortitus cibo tactus umbra ver depopulo cimentarius est torrens acquiro.", image: nil),
        NewsFeed(id: "0c2d3b9a-e7f4-465d-b81d-6961a8429f2a", name: "Rose Christiansen", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/529.jpg", content: "Atqui causa assumenda ancilla averto tenuis stultus. Antea calco doloribus urbanus succedo vulgivagus cruciamentum. Adficio repellendus sono audeo iusto vel.", image: "https://picsum.photos/seed/AtFIpjehr/600/400"),
        NewsFeed(id: "c68170f2-abe3-4cfc-ac06-873e59a5be63", name: "Lucy Feest", avatar: "https://avatars.githubusercontent.com/u/12056652", content: "Cattus quibusdam clementia umbra video vorax cogito defungo adimpleo. Iure concido bardus atavus terror tremo cuppedia vitae cribro. Esse adopto ab compono canis tondeo sperno amoveo. Capto comparo velum.", image: nil),
        NewsFeed(id: "6933a53f-18b1-4f2f-b510-c41f9a973aff", name: "Theodore Ziemann", avatar: "https://avatars.githubusercontent.com/u/41429422", content: "Carmen autus patruus debilito conqueror confugo vesco tendo spoliatio cavus. Alo tardus conventus caste absque curis. Tunc solus admiratio. Confido doloremque caterva baiulus. Curiositas sollers textilis maxime.", image: nil),
        NewsFeed(id: "6eeb3248-2772-45be-ad9d-ed39c5adb20c", name: "Forrest Kshlerin", avatar: "https://avatars.githubusercontent.com/u/24626066", content: "Utrum occaecati absens admitto tener at consuasor vergo accusator. Vulgaris amiculum utpote templum tener surculus civitas demergo. Sufficio ubi absens defetiscor casso amaritudo deprimo aetas umerus arcesso.", image: "https://picsum.photos/seed/LXkXu0Z/600/400"),
        NewsFeed(id: "ff9e958d-6b58-4a89-9bfe-c7658242ef20", name: "Guadalupe Kulas", avatar: "https://avatars.githubusercontent.com/u/14326569", content: "Tolero usque venio alioqui illo. Carpo adiuvo tyrannus vindico sursum.", image: nil),
        NewsFeed(id: "b9b598e8-2774-460e-ad1b-f31fc828d489", name: "Mr. Ian Macejkovic", avatar: "https://avatars.githubusercontent.com/u/52220656", content: "Conitor subseco tenuis voluptates mollitia quas.", image: nil),
        NewsFeed(id: "d97ed93d-a663-45a3-b1b2-dfd0019fbcda", name: "Christine Franey", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/126.jpg", content: "Ultra cometes barba spiritus cohaero uter amet adeo. Strues celer omnis. Denique tamdiu vestrum abutor amplexus ab laudantium arceo utique.", image: nil),
        NewsFeed(id: "0c2d3b9a-e7f4-465d-b81d-6961a8429f2a", name: "Rose Christiansen", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/529.jpg", content: "Atqui causa assumenda ancilla averto tenuis stultus. Antea calco doloribus urbanus succedo vulgivagus cruciamentum. Adficio repellendus sono audeo iusto vel.", image: "https://picsum.photos/seed/AtFIpjehr/600/400"),
        NewsFeed(id: "29c91560-5fe5-4248-8d19-b8719996557d", name: "Mark Connelly", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/49.jpg", content: "Celo sponte sodalitas talis vergo aliquid correptius substantia territo. Vaco clibanus adulescens videlicet. Caput tumultus carbo venia coerceo eligendi conicio denuncio damno pecco.", image: nil),
        NewsFeed(id: "8965c836-499b-487e-a5d8-869c8f5609de", name: "Miss Jodi Casper", avatar: "https://avatars.githubusercontent.com/u/50846889", content: "Tyrannus supra hic suus cimentarius aeternus cubitum xiphias.", image: nil),
        NewsFeed(id: "1e90fbf5-4b5a-4251-a277-75c0b4fb1a9c", name: "Joy Beahan", avatar: "https://avatars.githubusercontent.com/u/30935948", content: "Cena crinis comis aestus solvo absorbeo terga. Talio bestia votum. Hic tantillus esse amo.", image: nil),
        NewsFeed(id: "0c2d3b9a-e7f4-465d-b81d-6961a8429f2a", name: "Rose Christiansen", avatar: "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/529.jpg", content: "Atqui causa assumenda ancilla averto tenuis stultus. Antea calco doloribus urbanus succedo vulgivagus cruciamentum. Adficio repellendus sono audeo iusto vel.", image: "https://picsum.photos/seed/AtFIpjehr/600/400")
    ]
    func getData() {
        
    }
}
